[package]
name = "spidermonkey-wasm"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
spidermonkey-wasm-sys = { path = "../spidermonkey-wasm-sys" }
anyhow = "1.0.55"

[dev-dependencies]
spidermonkey-wasm-sys = { path = "../spidermonkey-wasm-sys", features = ["moz_debug"] }