name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    name: Test + Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download WASI-SDK
        run: sudo ./update-wasi-sdk.sh
      
      - name: Download SpiderMonkey build artifacts
        run: |
          cd crates/spidermonkey-wasm-sys/spidermonkey-wasm-build/
          ./download.sh
          cd -

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: 1.56.1
          default: true
          components: clippy, rustfmt

      - name: Cache .cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo
      
      - name: Cache cargo target
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
            ${{ runner.os }}-cargo-target
      
      - name: Install wasmtime-cli
        run: cargo install wasmtime-cli

      - name: Install cargo-wasi
        run: cargo install cargo-wasi

      - name: Test sys
        run: |
          cd crates/spidermonkey-wasm-sys
          cargo wasi test
          cd -

      - name: Lint
        run: cargo fmt -- --check
 
